### ISSUE TITLE
View all element in the map

### ISSUE THREAD

**Issue by jellypuno** [eclipse-che4z/che-che4z-explorer-for-endevor#113]
I would like to have the ability to view all the element in the map. In v11, this feature is available.

Possible Solution: Allow wildcard in all fields in the Endevor Location.

**Comment by nickImbirev** [comment]
The current problem is: we are not allowing wildcards in the 'environment' and 'stage number' location-profile properties, to make search result more specific. So, today, if users want to work with different environments - they have to create different location-profiles for each of them.

I can propose to remove this **coded** limitation. With this in mind, if there will be several environment/stage-numbers in the search result - we will add more layers into the tree. So, it will contain more mediation nodes.

**The only open question for now: how to provide ability for filtering within this gigantic tree....**

If the answer will be - return filters back (or something related to filters), maybe we can consider creating another tree view (from the previous version)?
For example, there can be a VSCode setting, which can control the tree view appearance. If somebody wants to work with specific locations - this setting will be activated and location profiles will be used, if not - we will switch to the old tree view that we had before, using one big map and filters.

@RedGoldPhoenix what do you think about it?

**Comment by RedGoldPhoenix** [comment]
@nickImbirev 
To have the same behavior as I had with the version 11 was great
I would like to see only what I have on the stage but not upper
Best Regards

**Comment by RedGoldPhoenix** [comment]
Hello @jellypuno and @nickImbirev 
Any update for this case ?
Best Regards

**Comment by nickImbirev** [comment]
> Hello @jellypuno and @nickImbirev Any update for this case ? Best Regards

Hey @RedGoldPhoenix , sorry for the delay.

Right now, we are working on this improvement within the issue #114 , we already have some results, that we can show to hear some feedback from you (before the actual release).
Once we will be ready for a quick demo or something like this - we will immediately let you know.

I hope it clarifies things

Best regards, Nikolai

**Comment by nickImbirev** [comment]
will be done within #114

**Comment by nickImbirev** [comment]
now, it is a very simple task to accomplish, because of the state management refactoring

**Comment by roman-kupriyanov** [comment]
Done in 1.8.0.
