### ISSUE TITLE
Respect VSCode 'enabledTrash' setting during files deletion

### ISSUE THREAD

**Issue by nickImbirev** [eclipse-che4z/che-che4z-explorer-for-endevor#116]
AS IS:
If I have the setting 'files.enableTrash' activated globally or in the E4E folder, I have this error: `Error: 'blahblah' to the recycle bin` during the element uploading into Endevor. Element is still uploaded, but I have to close outdated tab in VSCode manually and the error message does not look great.

TO BE:
E4E should respect the setting about enabled trash and delete files without recycle bin at all. So there should be no error messages, outdated tabs should be closed accordingly.

**Comment by roman-kupriyanov** [comment]
This one is somehow fixed in the current codebase.
