### ISSUE TITLE
Choosing a workspace for retrieve elements

### ISSUE THREAD

**Issue by nickImbirev** [eclipse-che4z/che-che4z-explorer-for-endevor#118]
As a user, I would love to work with several root folders opened in VSCode with opened E4E.

There is an ability to choose the primary workspace folder in VSCode. I think E4E can use it, and also it can store user choice in memory to prevent asking all the time.

**Comment by jellypuno** [comment]
**Notes:** 
- This is connected to our multi-workspace topic. So far our goal is to use the primary workspace.
- You can open several work folders in VS Code and it can contain git repos. If we open the multi-workspace it will affect our architecture.

**Comment by roman-kupriyanov** [comment]
We have this issue in our backlog.
