### ISSUE TITLE
Add support for Endevor tokens

### ISSUE THREAD

**Issue by nickImbirev** [eclipse-che4z/che-che4z-explorer-for-endevor#129]
As a user I cannot work with E4E with tokens from base profiles.

**Comment by jellypuno** [comment]
Research if it is possible to use the following tokens: 
- Endevor Web Service has its own token generation
- APIML token generation

**Comment by jellypuno** [comment]
Adding support means that we should be able to load tokenized profiles and also create profiles with tokens via E4E. 

1. How are we going to handle this in E4E if... (in terms of loading and using the profile)
   - The profile is created via CLI and the token is generated via CLI.
   - The profile is created via E4E and the token is generated in E4E. 

2. What if the user uses API Mediation Layer? What would be the precedence in using/creating the tokens?
   - Precedence would be if the user is connecting through APIML then the  token generated should be APIML tokens. If the user is connecting directly to Endevor Web Service then the token generated is from Endevor Web Service.

3. What if the token expires, how will the user acquire a new token without going through the CLI?

**Comment by uzuko001** [comment]
Partially resolved by #319 
Added endevor web services token support.

**Comment by uzuko001** [comment]
closing in favor of #322
