### ISSUE TITLE
Automatically show readonly Endevor reports in case of unsuccessful requests

### ISSUE THREAD

**Issue by nickImbirev** [eclipse-che4z/che-che4z-explorer-for-endevor#132]
There are several reports in all error responses from Endevor. Maybe we can show them to user by default or by active setting in VSCode?

**Comment by roman-kupriyanov** [comment]
Addressed in https://github.com/eclipse-che4z/che-che4z-explorer-for-endevor/pull/342 with introduction of the Endevor Activity view.
