### ISSUE TITLE
« Readonly mode » in Explorer for Endevor

### ISSUE THREAD

**Issue by FALLAI-Denis** [eclipse-che4z/che-che4z-explorer-for-endevor#148]
Hi

We are interested in the Explorer for Endevor extension. 

However, we wish to limit its access to consultation. 
Indeed we want to prohibit direct updating in Endevor because our reference is Git and we want all Endevor updates to be done through a Jenkins pipeline that ensures among other things the controls of source codes by Sonar.

We therefore want the provision of a parameterization that:
- either allows to disable the update function of Explorer for Endevor,
- or allows to activate each of the choices of the context menu on the Elements of Explorer for Endevor. 

Thanks.

**Comment by VitGottwald** [comment]
Hello @FALLAI-Denis , I assume you set up the security on the mainframe side so that the consultants cannot make changes right?

But you also want the Explorer for Endevor to be able to be set up to hide edit, generate, ... commands from the user.

Is that correct?

**Comment by roman-kupriyanov** [comment]
We have a follow up item for this in our backlog.
