### ISSUE TITLE
Create a Security.md file to specify policies of how to report vulnerabilities

### ISSUE THREAD

**Issue by nickImbirev** [eclipse-che4z/che-che4z-explorer-for-endevor#171]
It seems like Eclipse guys and Github itself is actively advocating to create a `Security.md` file to describe our policies for reporting vulnerabilities and policy violations.

I think it is reasonable to consider creation of this file. Maybe we can use existing templates, provided by Eclipse for us?

Template: https://github.com/eclipse/rdf4j/blob/main/SECURITY.md
GH tutorial: https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository
Template discussion: https://gitlab.eclipse.org/eclipse/dash/org.eclipse.dash.handbook/-/issues/150

**Comment by roman-kupriyanov** [comment]
Added here https://github.com/eclipse-che4z/che-che4z-explorer-for-endevor/pull/335
