### ISSUE TITLE
Printed element tab is not updated after editing

### ISSUE THREAD

**Issue by nickImbirev** [eclipse-che4z/che-che4z-explorer-for-endevor#178]
After refresh tree functionality is added, there is a case:
1. Click on an element in the tree (or multiple elements) to open tab(s) with element history and changes (Print element command).
2. Edit one element (or multiple elements) for which tab(s) opened and save the changes.
3. Previously opened Print element tab(s) is(are) not updated after changes applied.
4. Reopen tab(s) to see new changes to elements.

This behaviour may be misleading for the user, since the opened tab(s) will never be updated without user actions.

The approaches to that may be:
1. Close printed element tab(s) automatically if the change has happened.
2. Update a content of the tab together with a change (should be investigated, might be too difficult or might consume more time on re-requesting the content).
3. Put some identification to the opened tab(s) that a content is outdated and tab should be reopened (or implement some sort of Refresh tab button).

This is just a small notice about the user experience, nothing that requires immediate fixing.

**Comment by roman-kupriyanov** [comment]
Not going to be fixed, closing.
