### ISSUE TITLE
Automatic refresh of elements between opened locations

### ISSUE THREAD

**Issue by nickImbirev** [eclipse-che4z/che-che4z-explorer-for-endevor#185]
**Use case:** Today, if I use the `Add Element` or `Edit Element` functionalities of the E4E, I can specify any upload location in the Endevor map (even not visible in the current search location node).

**AS IS:** When I specify the upload location, which is covered by a different search location node - it is not updated, even after the successful response.

**TO BE:** When I specify the upload location, which is covered by a different search location node - it should be updated, after the successful response.

**Comment by roman-kupriyanov** [comment]
Not going to address it at the moment, closing.
