### ISSUE TITLE
It is impossible to add an element into the Endevor map without upper case

### ISSUE THREAD

**Issue by nickImbirev** [eclipse-che4z/che-che4z-explorer-for-endevor#186]
**Use case:** Today, I can add a new element into the Endevor, by selecting it from the file system. It can be a file with lower-case symbols.

**AS IS:** when the file name contains lower-case symbols - I see the error, that the element cannot be added.

**TO BE:** when the file name contains lower-case symbols and Endevor system requires names to be in the upper-case only - we need automatically convert the name into the upper-case.

**Comment by roman-kupriyanov** [comment]
Endevor error specifies the correct set of characters to be used. Considering the LONG NAME types support we should not modify the characters since in this case lower chars might be supported.
