### ISSUE TITLE
Add element icon is a bit confusing

### ISSUE THREAD

**Issue by nickImbirev** [eclipse-che4z/che-che4z-explorer-for-endevor#187]
Current `Add element` icon is a bit confusing, because it is used as an icon to create a new file in the VSCode. But we are not creating new files in Endevor, we are adding new elements from the local file system. 

Maybe we can consider to change it to something like this: `cloud-upload` icon from the VSCode icons?

Initially proposed by @IgorCATech

**Comment by roman-kupriyanov** [comment]
We should focus more on providing the Create Element feature, which looks more natural in vscode editing environment. Closing this for now.
