### ISSUE TITLE
Weird and non understandable validation message in the Endevor location dialogs

### ISSUE THREAD

**Issue by nickImbirev** [eclipse-che4z/che-che4z-explorer-for-endevor#191]
We have an issue in location dialogs:
When creating a location profile, my path is validated (which is fine), but I don't understand the error.
![image](https://user-images.githubusercontent.com/74672982/124292214-9dbc5280-db55-11eb-8276-248d40357e01.png)

I don’t know at this point which one is the "stage" field...where should I make corrections? Maybe we could include the text from the field that is failing validation?

**Comment by roman-kupriyanov** [comment]
Not going to be fixed, closing.
