### ISSUE TITLE
Compare dialogs are not working properly after the VSCode window reload

### ISSUE THREAD

**Issue by nickImbirev** [eclipse-che4z/che-che4z-explorer-for-endevor#198]
Scenario: A user tries to edit an Endevor element using E4E extension. The same Endevor element was modified by their colleague in the background (the changes were saved in the Endevor side). The user tries to upload their changes back to Endevor and gets the compare dialog (to compare the remote and the local versions of the element) opened. User decides to close the VSCode window and resolve the conflict later.

AS IS: when the user opens the VSCode window again, they got no compare dialogs open at all and when they try to upload their changes to Endevor again - they don't have `Apply` & `Discard` buttons available in the opened compare dialog.

**Comment by roman-kupriyanov** [comment]
Reopen it to continue fixing. At the moment we preserve the editing context on the window reload and the extension knows what opened editors are the elements in edit. But the issue that we may still have is not having this context until the extension is activated after restart. To properly fix that we have to introduce our own schema and URI for our elements, so we can use `onFileSystem:ndvr` type of activation event if there are element URI's are opened within the editors already.

**Comment by roman-kupriyanov** [comment]
Fixed in 1.7.0.
