### ISSUE TITLE
E4E does not respect already retrieved elements and dependencies

### ISSUE THREAD

**Issue by nickImbirev** [eclipse-che4z/che-che4z-explorer-for-endevor#211]
AS IS: E4E will overwrite the edited elements/retrieved elements and their dependencies during the command calls.

TO BE: I propose to ask users to confirm the overwrite action in the file system first, maybe we can even provide a different name for a local file in case of a name conflict.

**Comment by roman-kupriyanov** [comment]
Partially done in 1.8.0. E4E detects that a workspace folder is not empty and asks the user for continuation confirmation (potential data overwrite), but does not check precisely what files are going to be overwritten and do not allow an option to leave them both. It is not easy to achieve a behavior like that within the current structure of Retrieve commands (especisally, multi-element ones).
