### ISSUE TITLE
Convenient recovery after incorrect search of elements

### ISSUE THREAD

**Issue by nickImbirev** [eclipse-che4z/che-che4z-explorer-for-endevor#213]
When the user has some location used in the tree, they can expand the location node to start searching for the elements (even up the map). 

AS IS: today, E4E will just show an error notification, if the search location contains incorrect params and there are no elements returned from the Endevor WS (for example, in case of incorrect search system/subsystem/type declaration).

TO BE: it would be great to have a proper and convenient way to modify the search results right after the first wrong attempt to repeat the search attempt and possibly propagate the changes into the associated location profile.

**Comment by nickImbirev** [comment]
what we really can do as part of this issue is somehow indicate that the listElements request was successful, but we just could not find any element in this particular inventory location.

**Comment by roman-kupriyanov** [comment]
We will address it with the other items that are in our backlog.
