### ISSUE TITLE
Add element command is available, even if the location profile is incorrect

### ISSUE THREAD

**Issue by nickImbirev** [eclipse-che4z/che-che4z-explorer-for-endevor#220]
**The use case description:** The user created/chose a service profile and a location profile **with a wrong search location specified**. The user already tried to search for the elements in this location and was not able to find any element. After that, the user is trying to add an element from the local computer to the Endevor, using the same location profile.

**AS IS:** E4E allows user to add a new element and it will even prefill the upload location to the upload input box

**TO BE:** E4E should not allow to do this, if the user already tried to search for the elements unsuccessfully using the same location profile

**Comment by nickImbirev** [comment]
partially improved, because now, if the credentials or connection details are incorrect - the user won't be able to use the command

**Comment by roman-kupriyanov** [comment]
Closed. Fixed with the proper location profile statuses and recovery procedure is introduced.
