### ISSUE TITLE
Add an ability to compare the element between it's versions

### ISSUE THREAD

**Issue by nickImbirev** [eclipse-che4z/che-che4z-explorer-for-endevor#225]
I would like to have an ability to compare the fetched element with the element version up the Endevor map.

Also, it would be great to have an ability to select the target version from up the map to compare with.

**Comment by slackHer** [comment]
Yes, both of these things are great ideas! It will make mainframe code reviews SO much easier to do!

**Comment by zdmullen** [comment]
Questions:
Does the user want to compare between inventory locations (inv 1 and inv 2) or you want to compare element within 1 inventory location? The latter, probably, is more common 
Use up the map in the one location initially (with first found) to check changes in sandbox with same element you have up the map?
Render selection of up the map all elements?
How to manage multiple selection?

**Comment by slackHer** [comment]
Yes, the initial proposal is good. 

Regarding your other questions: 

- "Does the user want to compare between inventory locations (inv 1 and inv 2) or you want to compare element within 1 inventory location? The latter, probably, is more common"   I'm not sure what you mean by inventory location. 

For example, we use the following terminology: 

Location:                
  Environment. WRK          <--- Map location (up the map = W2, D1, D2, Q2, P2)
  System . . . DBSRV151     <--- Product Release "trunk"
  Subsystem. . US835897   <--- Sandbox or GA

To me, these 3 terms combined define an inventory location. So, comparing between two different trunks is not done often. Now, if you're talking about comparing a copy of an element between two sandboxes ... that would be nice. 

However, in general the request is to be able compare a version of an element with a version 'up the map'. 

- Use up the map in the one location initially (with first found) to check changes in sandbox with same element you have up the map? Yes, first found is a good place to start. However, it might be nice to be allowed to choose one from up the map. 

- Render selection of up the map all elements? Again, not sure what is meant here.  

This is what I'm thinking: right-click on an element and choose 'Select for compare', then go expand the [MAP] and right-click another element and choose 'Compare with selected'. Normally the element names will be the same. What we would like to do is be able to provide a side-by-side diff view of two versions of an element. It would be similar to using a Pull Request in Git where you select a file and Git shows differences between a branch and it's 'base branch'. 

@zdmullen I hope this makes sense.

**Comment by zdmullen** [comment]
Thank you, @slackHer. It does.

**Comment by dnk192** [comment]
I'm also looking for this enhancement.

**Comment by roman-kupriyanov** [comment]
There is an ability to compare all the change levels between each other in the Element History view (including levels up the map) starting with 1.8.0 release. We also added a compare local changes with the version of the element that were retrieved in the first place starting with 1.7.0.
