### ISSUE TITLE
Elements tree shows elements up the map in the wrong stage order

### ISSUE THREAD

**Issue by nickImbirev** [eclipse-che4z/che-che4z-explorer-for-endevor#231]
Currently, the E4E tree relies on the stage order: 1 and then 2 only.

I'm not sure, but, there might be a way, that the stage 2 can be first, so the Endevor map may look like this:
DEV/1 -> DEV/2 -> QA/2 -> QA/1 -> PRD/1 ...

So, apparently elements must be sorted according to the **stage sequence number** instead :(

**Comment by roman-kupriyanov** [comment]
We have an item for this in our backlog.
