### ISSUE TITLE
MOVE functionality 

### ISSUE THREAD

**Issue by JohnBMCR** [eclipse-che4z/che-che4z-explorer-for-endevor#234]
One of the primary use cases for Explorer for Endevor is the ability to allow non-zos users to in effect use Endevor but via the likes of EB4G and explorer for Endevor. 

Currently there are no facilities in Explorer for Endevor  to MOVE up the lifecyle. 

This either means that ZOWE CLI cmds have to be issued (which isn't exactly a user-friendly method), go inti 3270 Endevor (which of course defeats the purpose of EB4G and explorer for Endevor, or additional bespoke automation (which has to be managed as yet more software) invoking ZOWE CLI cmds. 

The obvious answer is MOVE functionality in  Explorer for Endevor.

**Comment by nickImbirev** [comment]
Hey @JohnBMCR!

Thank you so much for your feedback and a detailed enhancement request!

We will try to discuss it during the next issues grooming session, I hope we will prioritise your request.

Thank you again!

Best regards, Nikolai

**Comment by roman-kupriyanov** [comment]
Hi @JohnBMCR!

I am happy to announce that we introduced the MOVE capability with the 1.6.0 release. Please, check it out and create any other following up GitHub issues if you have any questions or suggestions.
