### ISSUE TITLE
Change the Left Click option on the element tree node

### ISSUE THREAD

**Issue by nickImbirev** [eclipse-che4z/che-che4z-explorer-for-endevor#270]
**AS IS:**
Current left click action on the element node is - Browse, which is ok, but not really intuitive and contradicts the overall VSCode UI.

**TO BE:**
The proposal is to make Edit as a primary left click action for the elements in the extension tree.

**Comment by zdmullen** [comment]
Pair this with a "Read-only" option where the behavior remains as the existing form?
Need to determine whether we edit in the extension (Explorer for Endevor) or in the file explorer as it is

**Comment by roman-kupriyanov** [comment]
Will be addressed in the following releases.
