### ISSUE TITLE
Allow switching Endevor connection profile

### ISSUE THREAD

**Issue by slavek-kucera** [eclipse-che4z/che-che4z-explorer-for-endevor#271]
I would like to have a button on the connection node in the e4e tree that would allow me to switch the connection profile.
Currently, if I want to utilize an alternative webservice I need to add a new connection and reattach all locations.

**Comment by roman-kupriyanov** [comment]
Thank you for opening the issue! 😃

**Comment by zdmullen** [comment]
Not likely that customers have access to same load libraries across instances
Perhaps we can implement a multiple select of profiles in the command palette?
Requires research with respect to the quick-pick itself.
