### ISSUE TITLE
Add simple and editable Endevor inventory filtering within the active session

### ISSUE THREAD

**Issue by nickImbirev** [eclipse-che4z/che-che4z-explorer-for-endevor#276]
As an E4E user I would like to have an opportunity to quickly search in the Endevor map without saving anything into the extension storage or load from the profiles. 

Just because sometimes I need to fix something quickly in my processors and I do not want to store and support this information anywhere.

**Comment by roman-kupriyanov** [comment]
We will address that in the following releases.
