### ISSUE TITLE
include the Ccid filter for the inventory search

### ISSUE THREAD

**Issue by Appurai** [eclipse-che4z/che-che4z-explorer-for-endevor#280]
**Is your feature request related to a problem? Please describe.**
when i try to filter the modules related to my application the entire inventory will be loaded , which is no need and would to get only my modules related to my application 

**Describe the solution you'd like**
If the modules filter is done based on the CCid  then it would be easy to get only the modules which is needed for my application

**Describe alternatives you've considered**
Even if the inventory filter is enable based on the element names which we need would also help, instead of downloading the entire inventory which would consume more time and then doing a find for the module.

**Additional context**
At present the ccid is available but is not accurate as all the elements are pulled even the ccid is mentioned as a filter

**Comment by zdmullen** [comment]
Hi @Appurai,
We've discussed this a bit in the team and want to enable both search by name (or multiple names) as well as CCID. Regarding CCID,  would you share some of the following information with us:
- How are your applications generally structured in Endevor? I assume you have elements across systems/subsystems if you are looking for the CCID search.
- Would you also like to have information about the last action associated with the element? We've been thinking about adding more element details than we currently have, and it seems to me that having the last operation would be important alongside the CCID
- Do you use the same CCID for an application throughout the Endevor map? Or do you use particular CCIDs for elements in development and then they get a different CCID as part of promotion etc.?
Many thanks for your feedback!

**Comment by Appurai** [comment]
Hi ,
1 .Applications structure in Endevor has elements across environment/
systems/subsystems and do a search on CCID  for looking for elements
2.yes, we would also like to have information about the last action
associated with the element and we think that having the last operation
would be important alongside the CCID
3. Yes ,we use the same CCID for an application throughout the Endevor map
from test till production ,as it will help us for tracking the changes
through the sdlc cycle

Thanks,
Appurai

**Comment by uzuko001** [comment]
Hello @Appurai , we have added CCID filter support in v.1.4.0. If you have any other concerns or suggestions feel free to create another issue.
