### ISSUE TITLE
Unable to retrieve elements based on their names individually

### ISSUE THREAD

**Issue by ajaxrreddy** [eclipse-che4z/che-che4z-explorer-for-endevor#291]
**Is your feature request related to a problem? Please describe.**
When ever we tried to pull elements it is pulling all the elements in that particular system/subsystem of that environment, rather than that if we have option to pull that particular element name which we wanted then that will help alot.

**Describe the solution you'd like**
There should be a provision to select element level as well, so we can pull particular elements in that environment.

**Describe alternatives you've considered**
Currently we are pulling all the elements in that environment and then working on them individually 

**Additional context**
None

**Comment by uzuko001** [comment]
Hi @ajaxrreddy 
Thank you for opening this request.
We are currently working on implementing a filter by element name which will be available for each inventory location in the explorer for endevor tree. It would give the ability to specify a comma-separated list of element names with or without wildcards to filter the three with.
Do you think this will fit your requirements?

**Comment by ajaxrreddy** [comment]
Yes, that will help.

**Comment by nickImbirev** [comment]
@ajaxrreddy please, check out the latest 1.4.0 E4E release for the update related to this issue

**Comment by uzuko001** [comment]
@ajaxrreddy I will close this issue, since we already implemented a name filter.
Feel free to re-open it or create a new one in case you would need it.
