### ISSUE TITLE
MFA support

### ISSUE THREAD

**Issue by azarrafa** [eclipse-che4z/che-che4z-explorer-for-endevor#293]
Hello,
That's the plugin support MFA authentication ? if so what are the prerequisites ?

**Comment by uzuko001** [comment]
Hello @azarrafa , we have added support for tokens generated by the Endevor Web Service.
Now the extension will check if they are configured and use them by default without any prerequisites.
If token generation is not configured we will fall back to using basic credentials for authentication.
It is also possible to disable the token usage from the extension settings.

Does this new feature help you and do you have any other questions or suggestions? Please let us know, thanks.

**Comment by uzuko001** [comment]
Hello @azarrafa,
as I mentioned above we implemented support for tokens generated by Endevor Web Service.
I am going to go ahead and close this, if you would like to see some other enhancement related to MFA support, please feel free to open another issue.
Thanks.
