### ISSUE TITLE
Upgrade the publishing GH actions versions to v1

### ISSUE THREAD

**Issue by nickImbirev** [eclipse-che4z/che-che4z-explorer-for-endevor#296]
I would propose to make a PR to update the packaging tools from the [v0](https://github.com/eclipse/che-che4z-explorer-for-endevor/blob/24f22c830965b48260550638693666ca8ef40735/.github/workflows/release-workflow.yml#L28) (currently used) to [v1](https://github.com/HaaLeo/publish-vscode-extension/releases/tag/v1) to have the latest versions used there. 

The tools used there are part of the custom GH action and the latest version of the action actually corresponds to the development versions we use inside the updated package.json file.

**Comment by uzuko001** [comment]
Thanks for opening this request @nickImbirev.
We plan to move publishing to our internal pipeline so I will close this issue.
