### ISSUE TITLE
[Workspace sync] Sync operation takes a lot of time on big inventory locations

### ISSUE THREAD

**Issue by nickImbirev** [eclipse-che4z/che-che4z-explorer-for-endevor#299]
_On behalf of @Appurai:_

It seems that the Sync operation tries to push (or pull?) all the elements were previously sync'ed into workspace every time, instead of affecting only the locally changed elements. For Fidelity it is about 500-1000 elements at once and may take more than 30 minutes.

This may be related to the white spaces which are automatically cleared out by the corresponding LS extension or those elements were changed remotely and the Pull operation (which is always happen during the sync) does update all the elements again.

Elements were used for Sync testing are of JCL type.

**Comment by nickImbirev** [comment]
I checked the Sync and Pull Operations behaviour on the E4E version 1.3.2 with VSCode version 1.73.

Usually, the sync operation uses the following sequence of HTTP requests:

1. One check connection request
2. One fetchEnvironment info request
3. One fetchSystem(s) info request
4. One fetchSubsystem(s) info request
5. One fetchType(s) info request
6. One fetchElements (in place) metadata (ALL) request
7. Two requests per each **modified** element (without any difference on where and how it was updated: on the backend side or via the E4E itself)

Even with big inventory locations, the problem should not be related to a number of all elements in the used location. There is a direct correlation only between the number of the **modified** elements and the number of the issued HTTP requests.

**Comment by nickImbirev** [comment]
@roman-kupriyanov @uzuko001 fyi

**Comment by nickImbirev** [comment]
@Appurai hello!

We started this small research after the conversation with you we had a few weeks ago.

May I ask you to help us with it a little bit? As for now, we are bit stuck, maybe you can provide us the version of the E4E and VSCode you are using while that issue was reproduced?

Also, may I ask you to send here a list of all extensions installed on your machine, if possible... Maybe some of them affects the local files somehow, so they become modified from our point of view.. This Stackoverflow [answer](https://stackoverflow.com/questions/35773299/how-can-you-export-the-visual-studio-code-extension-list) might be really helpful to fetch this info quickly.

Please, let me know if you need any other info or help with it

**Comment by roman-kupriyanov** [comment]
There were a lot of improvements to the workspace sync since this issue is open and we got not a lot of complaints about the performance, let's close this for now and keep monitoring.
