### ISSUE TITLE
Ability to view generated C headers ( *.CHDSECT) from ASMCHDR elements

### ISSUE THREAD

**Issue by IceNine46** [eclipse-che4z/che-che4z-explorer-for-endevor#304]
**Is your feature request related to a problem? Please describe.**
I cannot see generated ASMCHDR C headers (CHDSECT) in the product.  This forces me to either display a listing that includes the generated header, or go to ISPF Endevor to view the CHDSECT element.

I can edit and and modify the ASMCHDR elements, but cannot view their output.

**Describe the solution you'd like**
I would like to be able to view the CHDSECT elements in the product.  These are generated elements so they should be read only.

**Describe alternatives you've considered**
None

**Additional context**

**Comment by zdmullen** [comment]
Thanks for opening this issue. We will discuss it in the team and decide how best to provide support.

**Comment by roman-kupriyanov** [comment]
Hi @IceNine46,

We are considering to introduce a component list (similarly to ISPF) that may help you to discover and see the output components, including the C headers if they are produced.

This item will be tracked internally by us, so I am proceeding with closing this issue. Thanks!
