### ISSUE TITLE
E4E - Generate element automatically after save/update

### ISSUE THREAD

**Issue by MS615511** [eclipse-che4z/che-che4z-explorer-for-endevor#313]
**Is your feature request related to a problem? Please describe.**
It is not related to a problem. But this new feature will address a requirement to have a customer to adopt VSCode and E4E

**Describe the solution you'd like**
After changing an element and saving it, it will let E2E to go updating that element on Endevor. The request is to have somehow a generate action being executed right after a successful update.

**Describe alternatives you've considered**
An alternative is to use the mouse right click at the element and select the generate action.

**Additional context**
Customer support concerns that developers who are used to Endevor ispf interface, where generate of the element is automatically issued after an update of the element, may forget to command the generate when using E4E. If this happens it will cause to developers a problem of testing load objects that where not generated at the last updated element level.

**Comment by zdmullen** [comment]
Hi!
This would be quite a breaking change for the extension, but we will consider it when talking about 2.0 of the extension. We could also have a setting for it (to keep it on for the extension). We will have to look into this further. 
Thanks

**Comment by MS615511** [comment]
Hi,
Have you had a chance to review this?
Regards

**Comment by EmlynWill** [comment]
This would be useful, developers miss that they have to generate after update.
How about a pop up box (after the save) to ask the developer if they want to generate or not

**Comment by roman-kupriyanov** [comment]
Hi @MS615511, @EmlynWill.

Thanks for showing such an interest in this feature! I am pleased to announce that it's targeted to be addressed in the next minor Explorer for Endevor release which also is focused on enhancing the editing experience overall. Stay tuned for the updates!

Best regards,
Explorer for Endevor Team

**Comment by roman-kupriyanov** [comment]
Hi @MS615511 , @EmlynWill !

I am happy to inform you that we added a "Generate after upload" option selector before the element uploading. You may select if you want to generate the element after upload immediately during each upload attempt or remember your choice for all subsequent upload requests. There is an extension setting that allows you to set this option globally or for the workspace.

Check it out and let us know what do you think!

Thanks,
Roman

**Comment by roman-kupriyanov** [comment]
Hi @MS615511, @EmlynWill !

I am proceeding with closure of this issue. Please, if you will have any issues or questions regarding the generation after upload, reopen this issue or create a new one. Thanks!

Roman
