### ISSUE TITLE
Add APIML token support

### ISSUE THREAD

**Issue by uzuko001** [eclipse-che4z/che-che4z-explorer-for-endevor#322]
As an Explorer for Endevor user I would like to use APIML generated tokens for authentication

**Comment by uzuko001** [comment]
Questions to discuss: 
> Adding support means that we should be able to load tokenized profiles and also create profiles with tokens via E4E.
> 
> 1. How are we going to handle this in E4E if... (in terms of loading and using the profile)
>    
>    * The profile is created via CLI and the token is generated via CLI.
>    * The profile is created via E4E and the token is generated in E4E.
> 2. What if the user uses API Mediation Layer? What would be the precedence in using/creating the tokens?
>    
>    * Precedence would be if the user is connecting through APIML then the  token generated should be APIML tokens. If the user is connecting directly to Endevor Web Service then the token generated is from Endevor Web Service.
> 3. What if the token expires, how will the user acquire a new token without going through the CLI?

**Comment by roman-kupriyanov** [comment]
Questions discussed:

Adding support means that we should be able to load tokenized profiles and also create profiles with tokens via E4E.

1. How are we going to handle this in E4E if... (in terms of loading and using the profile)

    - The profile is created via CLI and the token is generated via CLI.
    - The profile is created via E4E and the token is generated in E4E.

> Both Zowe Team Config base profiles with API ML tokens created via CLI or ZE are supported. Profiles created via E4E at the moment do not support using of API ML, users have to utilize Zowe Team config to connect to API ML.

2. What if the user uses API Mediation Layer? What would be the precedence in using/creating the tokens?

    - Precedence would be if the user is connecting through APIML then the token generated should be APIML tokens. If the user is connecting directly to Endevor Web Service then the token generated is from Endevor Web Service.

> The order of precedence is:  Check for API ML token presence and use it if so, otherwise fallback to EWS token usage, if EWS token authentication disabled for the Endevor instance, fallback to basic username/password authentication. 

3. What if the token expires, how will the user acquire a new token without going through the CLI?

> After expiration the users are supposed to go to Zowe Explorer and use its built-in capabilities to login to API ML service which generate a new token in Team config (the same as `zowe login` command). Explorer for Endevor will automatically use updated tokens.
