### ISSUE TITLE
Keep the file open in the editor after a save or update Endevor action

### ISSUE THREAD

**Issue by IceNine46** [eclipse-che4z/che-che4z-explorer-for-endevor#350]
**Is your feature request related to a problem? Please describe.**
This is an enhancement request to change the behavior of a file being closed whenever a save or update operation is performed. 

As a developer, I frequently want to save my work to Endevor to either preserve changes or iteratively generate the element I am working on.   If I run into an assembly or compiler error, I have to reopen the file to fix the error, save (close), generate, reopen...,  this slows down the development process.   If I can save, generate, and have the listing pop up with the current file still editable, I can more quickly fix the error and generate again.

**Describe the solution you'd like**
Provide an option to determine if the file should be closed on save, or left within the editor/reopened automatically after a save.
The file tab should clearly indicate if there are changes in the current element that have not been saved. 

**Describe alternatives you've considered**
None

**Additional context**
Having the element close on save and requiring the developer to reopen the file manually each time adds additional clicks and time to the development process.

**Comment by zdmullen** [comment]
Hi @dnk192 -- the team is working on this now and has a branch with the split of editing and uploading. We would be happy to run it by you/share it in the near future for your feedback. How does that sound? Thanks

**Comment by dnk192** [comment]
That's great news, thanks!  I would be happy to test it out and provide feedback.

**Comment by roman-kupriyanov** [comment]
Hi @IceNine46,

We introduce a new approach that @zdmullen was talking about - "Disable the upload on save feature" for quite some time already in 1.7.0 release. Please, give it a try and let us know what do you think! Do not forget to disable Upload on save checkbox in the extension settings.

I will proceed with closing this issue. Feel free to open a new one if you have any questions. Thanks!
