### ISSUE TITLE
Listing file tab gets overwritten.

### ISSUE THREAD

**Issue by kenzlaz** [eclipse-che4z/che-che4z-explorer-for-endevor#351]
**Describe the bug**
Listing files tab gets overwritten when try to view listing for multiple files.

**To Reproduce**
Using VSCode Endevor for Explorer plugin, try to 'Print a Listing' for ex:
1. ELEMENT1.CPGM
2. ELEMENT2.LNK - This causes ELEMENT1.lst to be overwritten with ELEMENT2.lst
3. ELEMENT3.ASMPGM - This causes ELEMENT2.lst to be overwritten with ELEMENT3.lst

**Expected behavior**
Tabs for each listing file should be left open.

**Screenshots**

**Desktop (please complete the following information):**

- OS
MacOS Sonoma

- VSCode version
Version: 1.85.0 (Universal)
Commit: af28b32d7e553898b2a91af498b1fb666fdebe0c
Date: 2023-12-06T18:18:04.614Z (1 wk ago)
Electron: 25.9.7
ElectronBuildId: 25551756
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Darwin x64 23.1.0

- Extension version
Explorer for Endevor v1.5.4
**Zowe environment**
If applicable, add some information about the Zowe Environment that you use on your machine.

- Zowe CLI version
zowe --version = 7.18.7

- Zowe Explorer version
Zowe Explorer v2.12.2

**Comment by zdmullen** [comment]
Hi @kenzlaz,
The team will have a look at this soon and either introduce a fix for it or roll it into our next formal release. 
Thanks!

**Comment by roman-kupriyanov** [comment]
Hello @kenzlaz,

Thank you for reporting the issue. We were investigating it within a team and came to a conclusion that it might be related to the fact that the tabs for the listings are opened in so-called "preview" mode, which make them not to stay in the tab row if any new following tab is going to be opened, previous will be closed. To avoid that you can double-click on the tab's title to disable the preview mode. In this case it will stay in the tab row until you close it manually.

We are considering the option to disable preview mode by default for one of the following releases of Explorer for Endevor, thus all of the listing tabs opened will be staying in the tab row until you close them. But this option is currently only in the discussion.

Please, let us know if the suggestion would help in your case and if you have any other questions.

**Comment by kenzlaz** [comment]
Thx @roman-kupriyanov 
Disabling preview mode by default seems to be a good idea. Double clicking is tedious and i use it if i need to keep a specific tab open.

If preview mode is diabled, will unique tabs be open for an element with different types?
Ex: Unique tab each for PROG1.CPGM,  PROG1.LNK, etc.

**Comment by roman-kupriyanov** [comment]
Thanks for confirmation @kenzlaz ! We continue to investigate the possibilities to enhance the listing tabs behaviour.

Regarding your question about preserving the element tabs with different types and the same name, I can confirm that the different tabs will be opened. We distinguish the elements by not only the types, but by the entire element location - environment. stage, system, subsystem and etc. Thus, even if you have the same named element in different subsystems, to say, they all get own tab to work with.

**Comment by roman-kupriyanov** [comment]
Hi @kenzlaz !

I am happy to inform that we switched to use non-preview mode for the listing as a default in 1.7.0 version of Explorer.

Please give it a try and let us know if it made it work better for you. Thanks!

**Comment by roman-kupriyanov** [comment]
Hi @kenzlaz !

I am proceeding with closure of this issue. Please reopen this issue or create a new one if you will have any other issues or questions. Thanks!
