### ISSUE TITLE
Facing EWS1100E error in Explorer for Endevor while compiling the code. 

### ISSUE THREAD

**Issue by ssshreyas34** [eclipse-che4z/che-che4z-explorer-for-endevor#358]
**Describe the bug**
Facing EWS1100E error in Explorer for Endevor whenever compiling the code, even though the configuration is done and other operations like retrieve, print , delete are working fine. Can someone please help me on this its stopping my progress.

**Expected behavior**
Code should compile.

**Screenshots**
![Bug](https://github.com/eclipse-che4z/che-che4z-explorer-for-endevor/assets/64705522/8bd275df-5664-4215-ab12-f4a37f295756)

**Desktop (please complete the following information):**

- OS - Windows
- VSCode version - 1.85.1
- Extension version

**Zowe environment**
If applicable, add some information about the Zowe Environment that you use on your machine.

- Zowe CLI version
- Zowe Explorer version 2.13.0
- Zowe profiles information:
  - Used profile types
  - V1 profiles or Team Configuration file usage

_Note: you can upload the .zowe folder content in the issue (do not forget to remove the sensitive information from there) to help us reproduce the issue._

**Additional context**

**Comment by zdmullen** [comment]
Hi @ssshreyas34,
This looks like a core Endevor issue. We will consult our colleagues on that team and get back to you. 
Thanks for opening the issue.

**Comment by ssshreyas34** [comment]
Thank you for the response, Is this a global issue or something specific related to my Endevor setup?

**Comment by nmadavan** [comment]
Hello Mullen, I'm facing the same issue as stated by Shreyas. I'm using VS Code version 1.85 as well. Could you help us resolve this?

**Comment by roman-kupriyanov** [comment]
Hello @ssshreyas34 @nmadavan,

Thank you again for reporting the issue!

We were consulting with Endevor Core team about this specific issue. May I ask you to provide the Endevor execution report, which may contain more details about what exactly are happening with the type listing.

To get the execution report using the latest Explorer for Endevor, use the Activity view. To navigate there:

1. Enable bottom Panel in VSCode if not opened yet (a switcher is located at the top left corner of VSCode)

![image](https://github.com/eclipse-che4z/che-che4z-explorer-for-endevor/assets/91762867/d80ba4ee-cd59-4cac-9ef3-fa64d87f9e73)

2. In the Panel select the Activity view (Explorer for Endevor tab)

![image](https://github.com/eclipse-che4z/che-che4z-explorer-for-endevor/assets/91762867/b02fd832-a10c-45b0-89a9-0babc1e1bb68)

3. Click on failed generation event in the list to see the reports available for that event

![image](https://github.com/eclipse-che4z/che-che4z-explorer-for-endevor/assets/91762867/1d1ff822-a89e-41d5-a236-d1371b5a27f7)

4. Click on the execution report to open a new read-only tab and see the report content

Please copy the content of that tab (or you may use the File -> Save As... option of VSCode to create a file) and send it to us or add it to this issue (make sure it does not include any sensitive information).

**Comment by ssshreyas34** [comment]
Thank you responding back @roman-kupriyanov 
I'm attaching both the execution as well API report. 
![Capture](https://github.com/eclipse-che4z/che-che4z-explorer-for-endevor/assets/64705522/05ff90f5-04a6-4f6f-8514-9739f495f173)
[API report.txt](https://github.com/eclipse-che4z/che-che4z-explorer-for-endevor/files/13843162/API.report.txt)
[Execution report.txt](https://github.com/eclipse-che4z/che-che4z-explorer-for-endevor/files/13843164/Execution.report.txt)
Please take a look and let us know if you need any more information.

**Comment by roman-kupriyanov** [comment]
@ssshreyas34 thanks for providing the reports. We will continue investigation.

May I ask you to provide the details about the element editing operation you are trying to perform? 

- Did you try to edit element from up the map with a copyback to you work environment (which is DEVL/2/#WGMP/WGMP35)? 
- Or you are trying to edit the element in place?
- What environment your current Location profile is pointing out to (which named as prod/2/#IMMP/IMMP/COBOL)?

**Comment by ssshreyas34** [comment]
Hi @roman-kupriyanov -Thanks for taking out time and helping us. I will let you know the process which we are going through to edit the element.  We are performing two operations - 
1. Manually moving the element to DEVL using Endevor and later we are trying to edit the element using VS CODE for compilation.
2. The other way is we are retrieving the element in our local workspace and then setting up the Source Control by initializing it to Sync with Endevor For Explorer and trying to compile. 
3. Coming on to profile location it says PROD but even for DEVL we are facing the issue. 
I hope I answered your question, If not please let me know will explain it more detail.

**Comment by roman-kupriyanov** [comment]
Hi @ssshreyas34, thank you for the provided details!

I have spoken with the colleagues and they shared more info from the call you had last week. We took all the notes into consideration and we believe that the issue might be on the Endevor Web Services side and in the way how it operates with the type of configuration you have in your environment (in particular, the entry stage is 2).

My colleagues will follow up on the issue and provide you with the possible date of the availability for the fix in the Slack chat.

I will keep this issue opened, unless it is solved.

Thank you for cooperation and please, let us know if we can help you in your Explorer for Endevor adoption process in any other way 😉

**Comment by ssshreyas34** [comment]
Thank you so much @roman-kupriyano for all the support :)

**Comment by ssshreyas34** [comment]
Hello @roman-kupriyanov the above issue has now been resolved. We got great response and help from Broadcom team and our organization is now able to edit and move the components as we wanted to.
Thank you for all the support :)

**Comment by roman-kupriyanov** [comment]
Hello @ssshreyas34! Happy to hear that! Please do not hesitate to open another issue if you would need any help in the process 😃 

Closing this issue for now.
