### ISSUE TITLE
Deleting an element isn't enabled in Explorer for Endevor

### ISSUE THREAD

**Issue by ssshreyas34** [eclipse-che4z/che-che4z-explorer-for-endevor#362]
Hello Team,

We've recently begun working on integrating Explorer for Endevor into VS Code as an extension. So far, we've been able to perform various actions such as adding, modifying, and moving elements from our local workspace to Endevor. However, we've noticed that there isn't currently an option available for deleting an element. Would it be possible to enable this option? Having all kinds of actions available in a single place would be quite helpful.

Thanks,
Shreyas

**Comment by Morridt** [comment]
We've create a VSCode task to do this.  Refer to link below.
Under the **.vscode** folder create a **tasks.json** file with contents below.  
To run it, select '**Terminal**' from the menu bar and then '**Run task...**'

It will use your default Endevor Location Profile (zowe.config.json) to determine where to run it.

`{
    // See https://go.microsoft.com/fwlink/?LinkId=733558
    // for the documentation about the tasks.json format
    "version": "2.0.0",
    "tasks": [
        {
            "label": "Endevor: Delete Element",
            "type": "shell",
            "command": "zowe",
            "args": [
                "endevor",
                "delete",
                "element",
                "${input:Element}",
                "--type",
                "${input:Type}"
            ],
            "presentation": {
                "echo": false,
                "reveal": "always",
                "focus": true,
                "panel": "shared",
                "showReuseMessage": true,
                "clear": true
            },
        },
    ],
    "inputs": [
        {
            "type": "promptString",
            "id": "Element",
            "description": "Element:"
        },
        {
            "type": "promptString",
            "id": "Type",
            "description": "Type:"
        },
  ]
}`

**Comment by roman-kupriyanov** [comment]
Hi @ssshreyas34 @Morridt,

I am happy to inform you that we introduced a deletion action for the elements in the Elements view with our recent Explorer for Endevor 1.8.0 release. It should be enabled first in the extension settings 😉 

I will close this issue soon, but if you have any questions/suggestions, please open a new issue. Thanks!
