### ISSUE TITLE
Show Listing after Generate with Copyback

### ISSUE THREAD

**Issue by Morridt** [eclipse-che4z/che-che4z-explorer-for-endevor#363]
When doing a Generate With Copyback up the Endevor Map the extension is displaying the 'Show Listing' option.
If you select that option it is displaying the listing from the source environment (e.g. PROD) rather than the target environment (e.g. DEV).
As a workaround, going to the element generated in the DEV environment and selecting the 'Print a Listing' option displays the required listing.

**Describe the bug**
It displays the List Listing from the base element (ie PROD).

**To Reproduce**
'Generate with copyback' an element from up the map

**Expected behavior**
I suspect it should be displaying the listing just generated.

**Screenshots**
None...have to raise this externally

**Desktop (please complete the following information):**

- OS                          Windows
- VSCode version     1.85.2
- Extension version   v1.6.0

**Zowe environment**
If applicable, add some information about the Zowe Environment that you use on your machine.

- Zowe CLI version    7.20.1
- Zowe Explorer version   2.14.0
- Zowe profiles information:    Team Configuration file usage

_Note: you can upload the .zowe folder content in the issue (do not forget to remove the sensitive information from there) to help us reproduce the issue._

**Additional context**

**Comment by roman-kupriyanov** [comment]
Hello @Morridt, thank for the reporting the issue! I was able to reproduce it and you are right, the listing for the target element is expected. We are taking into the work. We will keep you posted about the progress in this thread.

**Comment by roman-kupriyanov** [comment]
HI @Morridt !

I am happy to inform you that we fixed this issue in 1.7.0 version, which was released recently. Now, it should show a proper listing for the copied back element, rather than for the element which was copied.

Please, give it a try and let us know! Thanks.

**Comment by Morridt** [comment]
Thanks!
Looking good

**Comment by roman-kupriyanov** [comment]
Thanks for confirmation! I am proceeding with closing this issue. If you have any other issues or questions, do not hesitate to open another issue 😉
