### ISSUE TITLE
ESEARCH through Endevor Explorer

### ISSUE THREAD

**Issue by calumtoddwork** [eclipse-che4z/che-che4z-explorer-for-endevor#365]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
We would like to see a right click, esearch option added to Endevor Explorer - same functionality as Endevor QuickEdit.

**Describe alternatives you've considered**
You can submit a CSV job through Zowe Explorer but it is not a one tool process.

**Additional context**
It would be good to right click on a location and have the option perform a text search (with the other options Hide / Delete an inventory location).

**Comment by zdmullen** [comment]
Thanks, @calumtoddwork! We have this planned as part of our next release.

**Comment by calumtoddwork** [comment]
@zdmullen Thanks Zach!
