### ISSUE TITLE
"OPTION NOCC" on browse action

### ISSUE THREAD

**Issue by FALLAI-Denis** [eclipse-che4z/che-che4z-explorer-for-endevor#38]
The "browse" action is a "PRINT ELEMENT ... OPTION BROWSE".
The result content is a "listing", not a "element".

I suggest that the "NOCC" option to be used, "PRINT ELEMENT ... OPTION BROWSE NOCC" to suppress header and the ASA code in column 1.

**Comment by nickImbirev** [comment]
I think we can just retrieve the element content without signing the element out. It will give us ability to show the element content only.

We can also implement a setting to provide ability to choose, which action will be executed during the element node left click action: PRINT with BROWSE option or VIEW element content.

**Comment by FALLAI-Denis** [comment]
Hi,

The actions proposed in Explorer for Endevor should be consistent with the actions proposed in the `@broadcom/endevor-for-zowe-cli` plugin: same action name = same result.

**Comment by uzuko001** [comment]
Hello @FALLAI-Denis, we have changed print element command in order to suppress the headers of elements.
Could you please check and let us know if the issue is resolved?

**Comment by uzuko001** [comment]
Hello @FALLAI-Denis,
please check my comment above. Feel free to open another issue if you would like to see other changes implemented.
Thanks.
